import = ["/home/notpc/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 14.5

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window.padding]
x = 11
y = 11
