;;; oauth2-auto-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from oauth2-auto.el

(autoload 'oauth2-auto-plist-sync "oauth2-auto" "\
Synchronously call ‘oauth2-auto-plist’ and return result.
For USERNAME and PROVIDER, see.

(fn USERNAME PROVIDER)")
(autoload 'oauth2-auto-access-token-sync "oauth2-auto" "\
Synchronously call ‘oauth2-auto-access-token’ and return result.
For USERNAME and PROVIDER, see.

(fn USERNAME PROVIDER)")

;;; End of scraped data

(provide 'oauth2-auto-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; oauth2-auto-autoloads.el ends here
