bind -T custom-prefix r run-shell -b "$HOME/.config/tmux/scripts/modes/show-which-key.sh cmd-palette-mode" \; switch-client -T cmd-palette-mode
bind -T cmd-palette-mode r run-shell "$HOME/.config/tmux/scripts/cmd-palette.sh run"
bind -T cmd-palette-mode b run-shell "$HOME/.config/tmux/scripts/cmd-palette.sh bg"
bind -T cmd-palette-mode l run-shell "$HOME/.config/tmux/scripts/cmd-palette.sh last"
bind -T cmd-palette-mode Escape switch-client -T custom-prefix
