name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # TODO: Test other OSs!
          #- macos-latest
          #- windows-latest
        emacs-version:
          - 28.2
          - 29.4
          - 30.1

    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.16.0

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      - name: Install requirements
        run: |
          echo "$HOME/.eask/bin" >> $GITHUB_PATH
          echo "$HOME/bin" >> $GITHUB_PATH

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.1
          components: clippy, rustfmt

      - name: Run tests
        run: |
          just build
          just test
