local r = require('keybinds.submaps.registry')

r.define('google-personal', 'reset', function(bind)
  bind('c', hl.dsp.focus({ workspace = 'name:calendar-personal' }), { description = 'Calendar' })
  bind('g', hl.dsp.focus({ workspace = 'name:gmail-personal' }),    { description = 'Gmail' })
  bind('y', hl.dsp.focus({ workspace = 'name:youtube-personal' }),  { description = 'YouTube' })
  bind('m', hl.dsp.focus({ workspace = 'name:meet-personal' }),     { description = 'Meet' })
  bind('escape', hl.dsp.submap('reset'),                            { description = 'Cancel' })
  bind('catchall', hl.dsp.submap('reset'))
end)
