local r = require('keybinds.submaps.registry')

r.define('google-work', 'reset', function(bind)
  bind('c', hl.dsp.focus({ workspace = 'name:calendar-work' }), { description = 'Calendar' })
  bind('g', hl.dsp.focus({ workspace = 'name:gmail-work' }),    { description = 'Gmail' })
  bind('y', hl.dsp.focus({ workspace = 'name:youtube-work' }),  { description = 'YouTube' })
  bind('m', hl.dsp.focus({ workspace = 'name:meet-work' }),     { description = 'Meet' })
  bind('escape', hl.dsp.submap('reset'),                        { description = 'Cancel' })
  bind('catchall', hl.dsp.submap('reset'))
end)
