require('keybinds.submaps.indicator')

require('keybinds.submaps.normal')
require('keybinds.submaps.window')
require('keybinds.submaps.monitor')
require('keybinds.submaps.move')
require('keybinds.submaps.resize')
require('keybinds.submaps.mouse')
require('keybinds.submaps.cursor')
require('keybinds.submaps.notes')
require('keybinds.submaps.notification')
require('keybinds.submaps.power')
require('keybinds.submaps.record')
require('keybinds.submaps.search')
require('keybinds.submaps.content')
require('keybinds.submaps.gaming')
require('keybinds.submaps.go')
require('keybinds.submaps.google')
require('keybinds.submaps.google_personal')
require('keybinds.submaps.google_work')
require('keybinds.submaps.personal')
require('keybinds.submaps.work')
require('keybinds.submaps.reserved_space')

hl.bind('SUPER + SUPER_L', hl.dsp.submap('normal'))
hl.bind('SUPER + O', hl.dsp.focus({ workspace = "-1" }))
hl.bind('SUPER + U', hl.dsp.focus({ workspace = "+1" }))
hl.bind('SUPER + SPACE', hl.dsp.focus({ workspace = "previous_per_monitor" }))

hl.bind('SUPER + mouse:272',         hl.dsp.window.drag(),   { mouse = true, description = 'Drag to move' })
hl.bind('SUPER + mouse:273',         hl.dsp.window.resize(), { mouse = true, description = 'Drag to resize' })
hl.bind('SUPER + Z',                 hl.dsp.window.drag(),   { mouse = true, description = 'Drag to move' })
