local r = require('keybinds.submaps.registry')

r.define('personal', function(bind)
  bind('t', hl.dsp.focus({ workspace = 'name:terminal-personal' }), { description = 'Terminal' })
  bind('b', hl.dsp.focus({ workspace = 'name:browser-personal' }),  { description = 'Browser' })
  bind('d', hl.dsp.focus({ workspace = 'name:discord-personal' }),  { description = 'Discord' })
  bind('w', hl.dsp.focus({ workspace = 'name:whatsapp-personal' }), { description = 'WhatsApp' })
  bind('q', hl.dsp.focus({ workspace = 'name:quran' }),             { description = 'Quran' })
  bind('g', hl.dsp.submap('google-personal'),                       { description = 'Google...' })
  bind('escape', hl.dsp.submap('reset'),                            { description = 'Cancel' })
  bind('catchall', hl.dsp.submap('reset'))
end)
