
[font]
size = 11

[font.bold]
family = "SauceCodePro Nerd Font Mono"

[font.italic]
family = "SauceCodePro Nerd Font Mono"

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[window.padding]
x = 11
y = 11

[env]
term = "xterm-256color"

[general]
import = ["/home/notpc/.config/alacritty/themes/catppuccin-mocha.toml"]

[terminal]

[terminal.shell] 
program = "tmux"

